#!/usr/bin/env python
# -*- coding: utf-8 -*-
""" quick and dirty script to generate a list of 'cp' commands for
item images.

"""
import sys
from os.path import abspath, join, dirname
from source_text import parse


def main(prefix):
    scr = abspath(join('../media', dirname(abspath(__file__)), 'items_game.txt'))
    for key, item in parse(scr)['items_game']['items'].iteritems():
	src = item['image_inventory']
	yield (key, prefix+src)


if __name__ == '__main__':
    try:
	source_dir = sys.argv[1]
    except (IndexError, ):
	print 'usage: %s source_directory (e.g., "/home/troy/pkg/incoming/output/")' % (sys.argv[0], )
    else:
	fmt = "cp %s.png %s.png"
	for key, image_file in main(source_dir):
	    print fmt % (image_file, key)

